from .partial_settings.allowed_hosts import *
from .partial_settings.apps import *
from .partial_settings.celery import *
from .partial_settings.db import *
from .partial_settings.localisation import *
from .partial_settings.logging import *
from .partial_settings.middleware import *
from .partial_settings.password_validators import *
from .partial_settings.rest_framework import *
from .partial_settings.smtp import *
from .partial_settings.static_media import *
from .partial_settings.templates import *
from .partial_settings.vars import *
