version: '3.1'

services:

  # BACKEND
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src/backend/
    restart: always
    env_file:
      - ./.env.dev
    depends_on:
      - db

  # DB
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=projectx
      - POSTGRES_PASSWORD=projectx
      - POSTGRES_DB=projectx
    env_file:
      - ./.env.dev

  # REDIS
  redis:
    image: redis
    restart: always

  # CELERY WORKER
  celery_worker:
    build: ./backend
    command: celery -A projectx worker --loglevel=INFO
    volumes:
      - ./backend/:/usr/src/backend/
    restart: always
    env_file:
      - ./.env.dev
    depends_on:
      - backend
      - redis

  # CELERY BEAT
  celery_beat:
    build: ./backend
    command: celery -A projectx beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend/:/usr/src/backend/
    restart: always
    env_file:
      - ./.env.dev
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:

